apiVersion: v1
kind: Secret
metadata:
  name: {{ include "main-node.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "main-node.name" . }}
    helm.sh/chart: {{ include "main-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $val := .Values.settings }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
