---
{{- if .Values.ingressGrpc.enabled -}}
{{- $fullName := include "main-node.fullname" . -}}
{{- $ingressPath := .Values.ingressGrpc.path -}}
{{- $ingressHttpsPort := .Values.service.httpsPort -}}
{{- $ingressHttpPort := .Values.service.httpPort -}}
apiVersion: {{.Values.ingress.apiVersion}}
kind: Ingress
metadata:
  name: {{ template "main-node.fullname" . }}-ingress-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "main-node.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.ingressGrpc.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingressGrpc.tls }}
  tls:
  {{- range .Values.ingressGrpc.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingressGrpc.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-grpc
              servicePort: 8001
  {{- end }}
{{- end }}