apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "main-node.fullname" . }}
{{- if .Values.image.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.image.imagePullSecrets | nindent 2 }}
{{- end }}