apiVersion: v1
kind: Service
metadata:
  name: {{ include "main-node.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "main-node.name" . }}
    helm.sh/chart: {{ include "main-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.pods.httpPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "main-node.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
