apiReplicaCount: 1

settings:


image:
  repository: registry.gitlab.com/grebble/backend/go-mono/grebble-main-node
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  httpPort: 80
  agentPort: 8080
  grpcPort: 8001


pods:
  httpPort: 80
  agentPort: 8080
  grpcPort: 8001


podSpec:
  openToNode: false

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 10Mi


tolerations: []

affinity: {}

strategy:
  type: RollingUpdate

ingressGrpc:
  enabled: false

ingress:
  enabled: false