name: test

on:
  push:
    branch:
      - 'main'
      - 'helm-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish helm chart
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts