replicaCount: 1

settings:
  MAIN_NODE_AGENT_ADDRESS: "main-node.grebble-main-node:8080"
  NSQ_NSQD: "nsq-nsqlookupd.nsq:4161"
  NSQ_PRODUCER_ADDRESS: "nsq-nsqd.nsq:4150"
  NSQ_API_ADDRESS: "http://nsq-nsqd.nsq:4151"

image:
  repository: registry.gitlab.com/grebble/backend/go-mono/grebble-agent
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  serviceNodePort: 80


resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 10Mi

tolerations: []

affinity: {}

ingress:
  enabled: false